export enum TEXT_CONSTANTS {
	CHAT_SESSION_PAGE_BACK = 'Back',
	CHAT_SESSION_PAGE_DESCRIPTION = 'View description',
	CHAT_SESSION_PAGE_TABLE_SCHEMA = 'Table schema',
	CHAT_SESSION_PAGE_SHARE = 'Share',
	CHAT_SESSION_PAGE_FULL_SCREEN = 'Full screen',
	CHAT_SESSION_PAGE_MINIMIZE = 'Minimize',
	CHAT_SESSION_PAGE_TABLE_VIEW = 'Table view',
	CHAT_SESSION_PAGE_CHART_VIEW = 'Chart view',
	CHAT_SESSION_PAGE_LIKE = 'Like',
	CHAT_SESSION_PAGE_DiSLIKE = 'Dislike',
	CHAT_SESSION_PAGE_LIKED = 'Liked',
	CHAT_SESSION_PAGE_DiSLIKED = 'Disliked',
	CHAT_SESSION_PAGE_DOWNLOAD = 'Download as CSV',
	CHAT_SESSION_PAGE_STEPS = 'Steps',
	MY_CONNECTION_PAGE_CARD_I_ICON = 'View description',

	HOME_PAGE_CHAT_PLACEHOLDER = 'Enter you unique Access ID',

}
